### ISSUE TITLE
Project dependency tree review

### ISSUE THREAD

**Issue by lottspot** [Lever-age/api#22]
Right now our project has a long list of dependencies. If we need all of them, we certainly shouldn't remove any, but I think it would be a good idea to examine them all and make sure we do in fact need everything we're pulling in. @kgdiem has done some work for us to remove unneeded dependencies from the package.json file, which leaves us with the following dependencies to review:

``` json
{
  "name": "leverage",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "body-parser": "^1.13.3",
    "compression": "^1.5.2",
    "cookie-parser": "^1.3.3",
    "express": "^4.13.3",
    "glob": "^6.0.4",
    "method-override": "^2.3.0",
    "morgan": "^1.6.1",
    "serve-favicon": "^2.3.0",
    "sqlite3": "^3.1.4"
  },
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-develop": "^0.4.0",
    "jsdoc": "^3.4.1",
    "load-grunt-tasks": "^3.2.0",
    "request": "^2.60.0",
    "time-grunt": "^1.2.1"
  }
}
```

Things I know right off the bat what their purpose is in our project:
- _express_: I know this is our API library
- _sqlite3_: Obvious need since our datastore is sqlite
- _jsdoc_: We discussed this one explicitly over the weekend

Things I understand have a purpose but maybe don't need to be project-wide:
- _all things grunt_: It looks like the Gruntfile is doing stuff which is probably just in use in one person's
  development environment. Since we don't have an asset pipeline or anything of the like,
  I'm not sure this has project-wide value.

That leaves the list of things I don't know what need they are being pulled in to fulfil: 
- _body-parser_
- _compression_
- _cookie-parser_
- _glob_
- _method-override_
- _morgan_
- _serve-favicon_
- _request_

I think we ought to discuss whether each of those libraries are needed, and what need they are fulfilling if they in fact are.

**Comment by kgdiem** [comment]
body-parser // makes request data available easily, eg POST name=kevin, would be available via req.body.name. Unnecessary in our current context
compression // unnecessary in our current context
cookie-parser // Probably unnessecary in our current context. Does the same thing as body parser... with cookies. 
glob // Used for wildcard file paths, I use it to require the controlllers/models eg require("*_/_.js")
method-override // came with the boilerplate, unnessecary
morgan // logger, no reason to remove it.
serve-favicon //serves favicon, Unnessecary

**Comment by kgdiem** [comment]
My proposed dependencies: 

"express": "^4.13.3",
"glob": "^6.0.4",
"morgan": "^1.6.1",
"sqlite3": "^3.1.4"

edit: 

Dev dependencies: 

"jsdoc": "^3.4.1"

**Comment by lottspot** [comment]
>  glob // Used for wildcard file paths, I use it to require the controlllers/models eg require("*/.js")

Fair enough.

> morgan // logger, no reason to remove it.

After peeking at the docs I have to confess, I loved this gem XD

> Named after Dexter, a show you should not watch until completion.

As far as our need for it goes though, I'm not sure that this is necessarily the kind of logging we want for the API. As far as I can tell, morgan provides the same function as webserver access and error logs, which in production would be provided by our webserver.

Don't get me wrong-- I'm certainly in favor of logging, and I'm very much in favor using a library for logging, but at the application layer we should be using a logger that will allow us to log generic messages such as detailed errors or dumps of debugging information. Something like [winston](https://github.com/winstonjs/winston) seems a lot better suited to that type of task.

**Comment by kgdiem** [comment]
Fair enough, Winston it is. We also might get some use out of helmet https://github.com/helmetjs/helmet/blob/master/README.md 

Upgrade insecure requests, same origin policy, remove X-powered-by header

**Comment by lottspot** [comment]
HTTP header manipulation is another one of those things that I think is better handled by the HTTP server rather than the backend application. Something like helmet would be useful if we needed to manipulate a HTTP header based on complex logic, but I'd say let's cross that bridge if/when we come to it.

**Comment by lottspot** [comment]
So based on our conversation thus far, it seems like we've come to a consensus on the following dependencies:
- _express_
- _glob_
- _winston_
- _sqlite3_

With the following dev dependencies:
- _jsdoc_

That seems to at least cover all of our immediate needs. If you agree with that assessment @kgdiem we can turn this thread into an actionable task

**Comment by lottspot** [comment]
This is probably also a good place to discuss what we should use for testing tools; personally, I have experience using mocha + chai. I am in no way married to using them for this project, but I do feel strongly that we need to select and agree upon one set of tools to use for all of our unit testing.

**Comment by kgdiem** [comment]
I'm fine with mocha/chai

**Comment by lottspot** [comment]
Mocha and chai have been added in #24; needs review
