### ISSUE TITLE
Implement /races endpoint

### ISSUE THREAD

**Issue by lottspot** [Lever-age/api#62]
This endpoint should return a list of information about all races. Each piece of race information must include:

- [ ] `race_id`
- [ ] Some human-readable identifier (e.g., "District Attorney Primary 2017")

**Comment by lottspot** [comment]
Also this should take a single parameter which, when provided, returns all races which match. Parameters:

- [ ] `race_id`

**Comment by enactdev** [comment]
Just pushed a new races endpoint with race_id as a possible parameter.
